views:
  - output: "about/index.html"
    template: "about.html"
  - output: "index.html"
    template: "landing.html"
  - output: "404.html"
    template: "404.html"

  - output: "statistics/index.html"
    query: "countries.rq"
    template: "statistics.html"
  - output: "statistics/statistics.svg"
    query: "countries.rq"
    template: "statistics.svg"
    unsafe: true

  - output: "topics/index.html"
    query: "topics.rq"
    template: "topic-list.html"
  - output: "{{safeName}}/index.html"
    query: "topics.rq"
    template: "topic-page.html"
  - output: "countries/index.html"
    query: "countries.rq"
    template: "country-list.html"
  - output: "{{safeName}}/index.html"
    query: "countries.rq"
    template: "country-page.html"

  - output: "sitemap.xml"
    query: "countries.rq"
    template: "sitemap.xml"
    unsafe: true

# orgs

  - output: "greenland/{{qid}}/index.html"
    query: "generators/greenland.rq"
    template: "org.html"
  - output: "sweden/{{qid}}/index.html"
    query: "generators/sweden.rq"
    template: "org.html"
  - output: "united-kingdom/{{qid}}/index.html"
    query: "generators/united-kingdom.rq"
    template: "org.html"
  - output: "denmark/{{qid}}/index.html"
    query: "generators/denmark.rq"
    template: "org.html"
  - output: "norway/{{qid}}/index.html"
    query: "generators/norway.rq"
    template: "org.html"
  - output: "ghana/{{qid}}/index.html"
    query: "generators/ghana.rq"
    template: "org.html"
  - output: "germany/{{qid}}/index.html"
    query: "generators/germany.rq"
    template: "org.html"
  - output: "south-africa/{{qid}}/index.html"
    query: "generators/south-africa.rq"
    template: "org.html"
